# Generated by Django 4.2.5 on 2023-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_age_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
